name: Grid Publish
on: [workflow_dispatch]
jobs:
  check-version:
    name: Check package version
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Check package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: Log when unchanged
        if: steps.check.outputs.is-new-version == 'false'
        run: 'echo "No version change"'
      - name: Cancel Workflow
        if: steps.check.outputs.is-new-version == 'false'
        uses: andymckay/cancel-action@0.2

  push-tag:
    needs: [check-version]
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Get package version
        id: version
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: Install
        run: |
          npm ci
      - name: npm install(toast.ui-grid)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm ci
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run build
      - name: Create Tag
        run: |
          git config --local user.email "jajugoguma@gmail.com"
          git config --local user.name "jajugoguma"
          git tag v${{ steps.version.outputs.committed-version }}
      - name: Push changes
        run: |
          git push origin v${{ steps.version.outputs.committed-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docs:
    needs: [push-tag]
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Get package version
        id: version
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: npm install
        run: |
          npm i -g @toast-ui/doc
          npm ci
      - name: npm install(toast.ui-grid)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm ci
      - name: Run doc
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run doc
          mv _${{ steps.version.outputs.committed-version }} ../../${{ steps.version.outputs.committed-version }}
          mv -i _latest ../../latest
          rm -rf tmpdoc
          git stash --include-untracked
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Commit files
        run: |
          git config --local user.email "jajugoguma@gmail.com"
          git config --local user.name "jajugoguma"
          rm -rf latest
          git stash pop
          git add .
          git commit -m "${{ steps.version.outputs.committed-version }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

  publish-package:
    needs: [push-tag]
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: https://registry.npmjs.org/
      - name: npm install
        run: |
          npm ci
      - name: npm install(toast.ui-grid)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm ci
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run build
      - name: Publish
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  publish-cdn:
    needs: [publish-package]
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: npm install
        run: |
          npm ci
      - name: npm install(toast.ui-grid)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm ci
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run build
      - name: Upload files to CDN
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run publish:cdn
        env:
          TOAST_CLOUD_TENENTID: ${{ secrets.TOAST_CLOUD_TENENTID }}
          TOAST_CLOUD_STORAGEID: ${{ secrets.TOAST_CLOUD_STORAGEID }}
          TOAST_CLOUD_USERNAME: ${{ secrets.TOAST_CLOUD_USERNAME }}
          TOAST_CLOUD_PASSWORD: ${{ secrets.TOAST_CLOUD_PASSWORD }}
