name: Grid Publish
on: [workflow_dispatch]

env:
  WORKING_DIRECTORY: ./packages/toast-ui.grid
  VUE_WRAPPER_DIRECTORY: ./packages/toast-ui.vue-grid
  REACT_WRAPPER_DIRECTORY: ./packages/toast-ui.react-grid
  CACHED_DEPENDENCY_PATHS: ./packages/toast-ui.grid/node_modules
  ROOT_DEPENDENCY_PATHS: ./node_modules
  CACHED_BUILD_PATHS: ./packages/toast-ui.grid/dist
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: install_dependencies
        id: cache-keys
        uses: ./.github/actions/install-dependencies
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
    outputs:
      root_cache_key: ${{ steps.cache-keys.outputs.root_cache_key }}
      grid_cache_key: ${{ steps.cache-keys.outputs.grid_cache_key }}

  build:
    name: Build
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/build-cache
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
          CACHED_BUILD_PATHS: ${{ env.CACHED_BUILD_PATHS }}
          ROOT_CACHE_KEY: ${{ needs.install_dependencies.outputs.root_cache_key }}
          GRID_CACHE_KEY: ${{ needs.install_dependencies.outputs.grid_cache_key }}
          BUILD_CACHE_KEY: ${{ env.BUILD_CACHE_KEY }}
    outputs:
      root_cache_key: ${{ needs.install_dependencies.outputs.root_cache_key }}
      grid_cache_key: ${{ needs.install_dependencies.outputs.grid_cache_key }}

  publish-package:
    needs: [build]
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: https://registry.npmjs.org/
      - name: Check dependency cache
        uses: actions/cache@v2
        with:
          path: ${{ env.ROOT_DEPENDENCY_PATHS }}
          key: ${{ needs.build.outputs.root_cache_key }}
      - name: Check dependency cache (toast.ui-grid)
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ needs.build.outputs.grid_cache_key }}
      - name: Check build cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHED_BUILD_PATHS }}
          key: ${{ env.BUILD_CACHE_KEY }}
      - name: Publish
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: ls
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    outputs:
      root_cache_key: ${{ needs.build.outputs.root_cache_key }}
      grid_cache_key: ${{ needs.build.outputs.grid_cache_key }}