name: Grid Publish
on: [workflow_dispatch]
jobs:
  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Check package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: Log when unchanged
        if: steps.check.outputs.is-new-version == 'false'
        run: 'echo "No version change"'
      - name: Cancel Workflow
        if: steps.check.outputs.is-new-version == 'false'
        uses: andymckay/cancel-action@0.2

  deploy-doc:
    needs: [checkVersion]
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Get package version
        id: version
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: npm install
        run: |
          npm i -g @toast-ui/doc
          npm ci
      - name: npm install(toast.ui-grid)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run build
      - name: Run doc
        run: |
          npm run doc
          mv apps/toast-ui.grid/${{ steps.version.outputs.committed-version }} ${{ steps.version.outputs.committed-version }}
          mv -i apps/toast-ui.grid/_latest latest
          git stash --include-untracked
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Commit files
        run: |
          git config --local user.email "js87zz.lee@nhn.com"
          git config --local user.name "js87zz"
          git stash pop
          git add .
          git commit -m "${{ steps.version.outputs.committed-version }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
  tag:
    needs: [checkVersion]
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Get package version
        id: version
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: Install
        run: |
          npm install
      - name: npm install(toast.ui-grid)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run build
      - name: Create Tag
        run: |
          git config --local user.email "js87zz.lee@nhn.com"
          git config --local user.name "js87zz"
          git tag v${{ steps.version.outputs.committed-version }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: [checkVersion]
    env:
      WORKING_DIRECTORY: ./packages/toast-ui.grid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
      - name: npm install(toast.ui-grid)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
          ls -al
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run build
      - name: Publish
        run: npm publish
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
