name: Publish grid
on: [workflow_dispatch]

env:
  WORKING_DIRECTORY: ./packages/toast-ui.grid
  VUE_WRAPPER_DIRECTORY: ./packages/toast-ui.vue-grid
  REACT_WRAPPER_DIRECTORY: ./packages/toast-ui.react-grid
  CACHED_DEPENDENCY_PATHS: ./packages/toast-ui.grid/node_modules
  ROOT_DEPENDENCY_PATHS: ./node_modules
  CACHED_BUILD_PATHS: ./packages/toast-ui.grid/dist
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: install_dependencies
        id: cache-keys
        uses: ./.github/actions/install-dependencies
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
    outputs:
      root_cache_key: ${{ steps.cache-keys.outputs.root_cache_key }}
      grid_cache_key: ${{ steps.cache-keys.outputs.grid_cache_key }}

  build:
    name: Build
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/build-cache
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
          CACHED_BUILD_PATHS: ${{ env.CACHED_BUILD_PATHS }}
          ROOT_CACHE_KEY: ${{ needs.install_dependencies.outputs.root_cache_key }}
          GRID_CACHE_KEY: ${{ needs.install_dependencies.outputs.grid_cache_key }}
          BUILD_CACHE_KEY: ${{ env.BUILD_CACHE_KEY }}
    outputs:
      root_cache_key: ${{ needs.install_dependencies.outputs.root_cache_key }}
      grid_cache_key: ${{ needs.install_dependencies.outputs.grid_cache_key }}

  push-tag:
    needs: [check-version, build]
    name: Push tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: https://registry.npmjs.org/
      - name: Get package version
        id: version
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: Create Tag
        run: |
          git config --local user.email "jajugoguma@gmail.com"
          git config --local user.name "jajugoguma"
          git tag v${{ steps.version.outputs.committed-version }}
      - name: Push changes
        run: |
          git push origin v${{ steps.version.outputs.committed-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-package:
    needs: [check-version, build]
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish package
        uses: ./.github/actions/publish-package
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
          CACHED_BUILD_PATHS: ${{ env.CACHED_BUILD_PATHS }}
          ROOT_CACHE_KEY: ${{ needs.build.outputs.root_cache_key }}
          GRID_CACHE_KEY: ${{ needs.build.outputs.grid_cache_key }}
          BUILD_CACHE_KEY: ${{ env.BUILD_CACHE_KEY }}

  publish-cdn:
    needs: [check-version, build]
    name: Publish to CDN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Publish to CDN
        uses: ./.github/actions/publish-to-cdn
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
          CACHED_BUILD_PATHS: ${{ env.CACHED_BUILD_PATHS }}
          ROOT_CACHE_KEY: ${{ needs.build.outputs.root_cache_key }}
          GRID_CACHE_KEY: ${{ needs.build.outputs.grid_cache_key }}
          BUILD_CACHE_KEY: ${{ env.BUILD_CACHE_KEY }}

  publish-docs:
    needs: [check-version, build]
    name: Publish documents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Publish documents
        uses: ./.github/actions/publish-docs
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
          ROOT_CACHE_KEY: ${{ needs.build.outputs.root_cache_key }}
          GRID_CACHE_KEY: ${{ needs.build.outputs.grid_cache_key }}