name: Grid Publish
on: [workflow_dispatch]

env:
  WORKING_DIRECTORY: ./packages/toast-ui.grid

jobs:
  publish-wrapper:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
        registry-url: https://registry.npmjs.org/
    - name: Get package version
      id: version
      uses: PostHog/check-package-version@v2
      with:
        path: ${{ env.WORKING_DIRECTORY }}/
    - name: Update package.json of wrappers
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run update:wrapper
    - name: Commit files
        run: |
          git config --local user.email "jajugoguma@gmail.com"
          git config --local user.name "jajugoguma"
          git add .
          git commit -m "chore: update version of wrappers to v${{ steps.version.outputs.committed-version }}"